In [4]:
import numpy as np

### Creating Arrays

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(5, 8)

array([8, 8, 8, 8, 8])

In [8]:
a = np.array([1, 2, 3, 5, 7, 11])
a

array([ 1,  2,  3,  5,  7, 11])

In [9]:
a[2]

np.int64(3)

In [10]:
a[2] = 13

In [11]:
a

array([ 1,  2, 13,  5,  7, 11])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi Dimensional Arrays

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
n[0]

array([ 1, 20,  3])

In [21]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
n[:, 1]

array([20,  5,  1])

In [23]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly Generated Arrays

In [24]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [25]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [26]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [27]:
np.random.seed(8)
np.random.randint(low=0, high=100, size=(5, 2))

array([[67, 84],
       [ 5, 90],
       [ 8, 83],
       [63, 48],
       [85, 60]])

### Element-wise Operations

In [30]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a + 1

array([1, 2, 3, 4, 5])

In [32]:
(10 + (a * 2)) ** 2

array([100, 144, 196, 256, 324])

In [33]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [35]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison Operations

In [37]:
a >= 2

array([False, False,  True,  True,  True])

In [38]:
a > b

array([False, False,  True,  True,  True])

In [39]:
a[a > b]

array([2, 3, 4])